# Generated by Django 5.1.5 on 2025-01-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='constitution',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pet',
            name='dexterity',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pet',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='experience_to_next_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='intelligence',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pet',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='luck',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pet',
            name='strength',
            field=models.IntegerField(default=5),
        ),
    ]
