from pets.models import Item
import random

def run():
    # List of items to populate
    items = [
        {
            "name": "Apple",
            "description": "A tasty fruit.",
            "price": 5,
            "is_food": True,
            "is_toy": False,
            "health_increase": 10,
            "happiness_increase": 5,
            "energy_increase": 2,
        },
        {
            "name": "Bone",
            "description": "A fun toy for pets.",
            "price": 15,
            "is_food": False,
            "is_toy": True,
            "health_increase": 0,
            "happiness_increase": 20,
            "energy_increase": 0,
        },
        {
            "name": "Fish",
            "description": "A fresh fish.",
            "price": 10,
            "is_food": True,
            "is_toy": False,
            "health_increase": 15,
            "happiness_increase": 10,
            "energy_increase": 5,
        },
        {
            "name": "Ball",
            "description": "A bouncy ball for playtime.",
            "price": 8,
            "is_food": False,
            "is_toy": True,
            "health_increase": 0,
            "happiness_increase": 25,
            "energy_increase": 0,
        },
        {
            "name": "Milk",
            "description": "A glass of warm milk.",
            "price": 6,
            "is_food": True,
            "is_toy": False,
            "health_increase": 8,
            "happiness_increase": 7,
            "energy_increase": 3,
        },
        {
            "name": "Cheese",
            "description": "A small block of cheese.",
            "price": 7,
            "is_food": True,
            "is_toy": False,
            "health_increase": 12,
            "happiness_increase": 10,
            "energy_increase": 4,
        },
        {
            "name": "Stick",
            "description": "A simple stick to play fetch.",
            "price": 3,
            "is_food": False,
            "is_toy": True,
            "health_increase": 0,
            "happiness_increase": 15,
            "energy_increase": 0,
        },
        {
            "name": "Carrot",
            "description": "A crunchy carrot.",
            "price": 4,
            "is_food": True,
            "is_toy": False,
            "health_increase": 5,
            "happiness_increase": 5,
            "energy_increase": 2,
        },
        {
            "name": "Frisbee",
            "description": "A frisbee for outdoor fun.",
            "price": 20,
            "is_food": False,
            "is_toy": True,
            "health_increase": 0,
            "happiness_increase": 30,
            "energy_increase": 0,
        },
        {
            "name": "Bread",
            "description": "A slice of bread.",
            "price": 5,
            "is_food": True,
            "is_toy": False,
            "health_increase": 7,
            "happiness_increase": 4,
            "energy_increase": 1,
        },
        {
            "name": "Cookie",
            "description": "A sweet treat.",
            "price": 6,
            "is_food": True,
            "is_toy": False,
            "health_increase": 3,
            "happiness_increase": 20,
            "energy_increase": 2,
        },
        {
            "name": "Rubber Duck",
            "description": "A squeaky rubber duck.",
            "price": 9,
            "is_food": False,
            "is_toy": True,
            "health_increase": 0,
            "happiness_increase": 18,
            "energy_increase": 0,
        },
        {
            "name": "Sausage",
            "description": "A delicious sausage link.",
            "price": 12,
            "is_food": True,
            "is_toy": False,
            "health_increase": 15,
            "happiness_increase": 10,
            "energy_increase": 4,
        },
        {
            "name": "Pillow",
            "description": "A comfy pillow for resting.",
            "price": 25,
            "is_food": False,
            "is_toy": False,
            "health_increase": 10,
            "happiness_increase": 5,
            "energy_increase": 15,
        },
        {
            "name": "Ham",
            "description": "A thick slice of ham.",
            "price": 18,
            "is_food": True,
            "is_toy": False,
            "health_increase": 20,
            "happiness_increase": 12,
            "energy_increase": 5,
        },
    ]

    # Add items to the database
    for item_data in items:
        item, created = Item.objects.get_or_create(
            name=item_data["name"],
            defaults={
                "description": item_data["description"],
                "price": item_data["price"],
                "is_food": item_data["is_food"],
                "is_toy": item_data["is_toy"],
                "health_increase": item_data["health_increase"],
                "happiness_increase": item_data["happiness_increase"],
                "energy_increase": item_data["energy_increase"],
            },
        )
        if created:
            print(f"Created item: {item.name}")
        else:
            print(f"Item already exists: {item.name}")
